#!/bin/bash
#SBATCH --mail-user=cxg454@case.edu
#SBATCH --mail-type=ALL
#SBATCH --time 1:00:00
#SBATCH --exclusive
#SBATCH -N 1
#SBATCH -n 40
#SBATCH --mem=0
#SBATCH -J xsf

ext=liv2o5

bsc="env OMP_NUM_THREADS=40 MKL_NUM_THREADS=40 srun -n 1 bse --optdfl=optdatac.h5 --tmesh=0x40 --v8  ctrl.${ext}"

# dark/bright exciton
spin=sp2
xtn=brt
num1=11
num2=12
num3=21
num4=22
e="1.75,1.76"
a="1.75-1.76"


##  calculating the electron-hole psi probability  ###
#$bsc --wexpsi~ewin=13.3,13.5eV~r-=0.101180,0.250,0.8917p~fn=v2o5-de-v-new.xsf  > v2o5-de-v-new.log  # new calculation
$bsc --wexpsi~ewin=${e}eV~r-=0.1506870,0.0000000,0.6075330p~fn=${ext}-${xtn}-${spin}-${a}-v${num1}.xsf  > ${ext}-${spin}-${a}-v${num1}.log
$bsc --wexpsi~ewin=${e}eV~r-=0.8493130,0.0000000,0.6075330p~fn=${ext}-${xtn}-${spin}-${a}-v${num2}.xsf  > ${ext}-${spin}-${a}-v${num2}.log
$bsc --wexpsi~ewin=${e}eV~r-=0.3493130,0.5000000,0.3924670p~fn=${ext}-${xtn}-${spin}-${a}-v${num3}.xsf  > ${ext}-${spin}-${a}-v${num3}.log
$bsc --wexpsi~ewin=${e}eV~r-=0.6506870,0.5000000,0.3924670p~fn=${ext}-${xtn}-${spin}-${a}-v${num4}.xsf  > ${ext}-${spin}-${a}-v${num4}.log
#$bsc --wexpsi~ewin=${e}eV~r+=0.104340,0.250,0.5311p~fn=${ext}-${xtn}-${spin}-${a}-ov.xsf > ${ext}-${spin}-${a}-ov.log
#$bsc --wexpsi~ewin=${e}eV~r+=-0.06893,0.250,0.0031p~fn=${ext}-${xtn}-${spin}-${a}-oc.xsf > ${ext}-${spin}-${a}-oc.log
#$bsc --wexpsi~ewin=${e}eV~r+=0.250000,0.250,0.0012p~fn=${ext}-${xtn}-${spin}-${a}-ob.xsf > ${ext}-${spin}-${a}-ob.log
